// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfincuvgvqehireiwmww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmaW5jdXZndnFlaGlyZWl3bXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTIxODUsImV4cCI6MjA1OTA4ODE4NX0._3ItJ92rnYFYU961CZkoq6UfrXXw_VOU79EKWY-4Dc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);